require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "Rakefile"

Metrics/AbcSize:
  Max: 30

Naming/MethodParameterName:
  AllowedNames:
    - id
    - ns
    - db
    - to

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4
